"""
NCA -- Zero-Maintenance Auto-Discovery Profiler Generator
=========================================================
Finds EVERY public function in core/**/*.hpp by itself.
No arguments needed. No manual updating. Ever.

How it works:
  1. Discovers its own location via __file__
  2. Walks ../core/ for all .hpp files
  3. Extracts function prototypes via regex
  4. Generates test_auto_generated.cpp that uses C++ TMP (autotest.hpp)
     to allocate arguments and benchmark automatically
"""

import os, glob, re, pathlib

def main():
    # --- Auto-discover workspace from script location ---
    script_dir = pathlib.Path(__file__).resolve().parent          # .../tests/
    project_root = script_dir.parent                               # .../nn/
    core_dir = project_root / "core"
    output_file = script_dir / "test_auto_generated.cpp"

    print(f"  [autogenerate] Scanning: {core_dir}")
    print(f"  [autogenerate] Output:   {output_file}")

    # --- Glob every header in core/ recursively ---
    headers = sorted(core_dir.rglob("*.hpp"))
    funcs = []

    for h in headers:
        content = h.read_text(encoding="utf-8", errors="ignore")

        # Extract the first namespace declaration
        ns_match = re.search(r'namespace\s+([a-zA-Z0-9_:]+)\s*\{', content)
        ns = ns_match.group(1) if ns_match else ""

        # Skip SIMD backend internals — we test the dispatch layer, not the raw kernels
        if 'simd' in ns:
            continue

        # Match free function declarations: void/float name(args);
        for m in re.finditer(r'^\s*(?:float|void)\s+([a-zA-Z0-9_]+)\s*\(([^)]*)\)\s*;', content, re.MULTILINE):
            name = m.group(1)
            # Skip inline helpers that aren't real API
            if name in ('extract_e8m0', 'decode_e8m0_scale'):
                continue
            funcs.append(f"{ns}::{name}")

    # --- Generate C++ ---
    rel_headers = [h.relative_to(project_root).as_posix() for h in headers]

    with open(output_file, 'w', encoding='ascii') as f:
        f.write('// Auto-generated by autogenerate.py -- DO NOT EDIT\n')
        f.write('#include "tests/autotest.hpp"\n')
        for rh in rel_headers:
            f.write(f'#include "{rh}"\n')

        f.write('\nint main() {\n')
        f.write('    nca::simd::detect();\n')
        f.write('    nca::testing::print_hardware_info();\n\n')

        for fn in funcs:
            f.write(f'    nca::testing::run_benchmark("{fn}", &{fn});\n')

        f.write('    return 0;\n}\n')

    print(f"  [autogenerate] Registered {len(funcs)} functions from {len(headers)} headers.")

if __name__ == '__main__':
    main()
