// Auto-generated by autogenerate.py -- DO NOT EDIT
#include "tests/autotest.hpp"
#include "core/activations.hpp"
#include "core/layers/glr.hpp"
#include "core/layers/halting.hpp"
#include "core/layers/mlp.hpp"
#include "core/layers/sla.hpp"
#include "core/layers/ssm.hpp"
#include "core/linalg/mx_linear.hpp"
#include "core/normalization.hpp"
#include "core/simd/avx2_kernels.hpp"
#include "core/simd/avx2_math.hpp"
#include "core/simd/avx512_kernels.hpp"
#include "core/simd/avx512_math.hpp"
#include "core/simd/avx512_vnni.hpp"
#include "core/simd/cache_policy.hpp"
#include "core/simd/dispatch.hpp"
#include "core/vision/scanner.hpp"

int main() {
    nca::simd::detect();
    nca::testing::print_hardware_info();

    nca::testing::run_benchmark("nca::math::silu", &nca::math::silu);
    nca::testing::run_benchmark("nca::layers::glr_step", &nca::layers::glr_step);
    nca::testing::run_benchmark("nca::layers::halting_step", &nca::layers::halting_step);
    nca::testing::run_benchmark("nca::layers::fused_gated_silu_quantize", &nca::layers::fused_gated_silu_quantize);
    nca::testing::run_benchmark("nca::layers::gated_mlp_step", &nca::layers::gated_mlp_step);
    nca::testing::run_benchmark("nca::layers::sla_step", &nca::layers::sla_step);
    nca::testing::run_benchmark("nca::layers::ssm_step", &nca::layers::ssm_step);
    nca::testing::run_benchmark("nca::layers::mx_fused_ssm_silu_quantize_step", &nca::layers::mx_fused_ssm_silu_quantize_step);
    nca::testing::run_benchmark("nca::linalg::mx_quantize_w", &nca::linalg::mx_quantize_w);
    nca::testing::run_benchmark("nca::linalg::mx_quantize_x", &nca::linalg::mx_quantize_x);
    nca::testing::run_benchmark("nca::linalg::mx_fused_silu_quantize_x", &nca::linalg::mx_fused_silu_quantize_x);
    nca::testing::run_benchmark("nca::linalg::mx_dot", &nca::linalg::mx_dot);
    nca::testing::run_benchmark("nca::math::rmsnorm", &nca::math::rmsnorm);
    nca::testing::run_benchmark("nca::vision::dwconv2d_3x3", &nca::vision::dwconv2d_3x3);
    nca::testing::run_benchmark("nca::vision::ssm2d_scan", &nca::vision::ssm2d_scan);
    return 0;
}
